---
name: First GitHub Action
on:
  push:
    branches:
      - main
 jobs:
    build   :
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Say Visca Barca!
          run: echo "Visca Barca! with Github Actions"

